[package]
name = "rust-socket"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mio = { version = "1.0.2", features = ["os-poll", "net"] }
rayon = "1.10.0"